import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WalletProvider from "@/context/WalletProvider";
import { ContractDataProvider } from "@/context/ContractDataProvider";
import { Toaster } from 'react-hot-toast';
import { LayoutContent } from "@/components/LayoutContent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-radial min-h-screen`}
      >
        <WalletProvider>
          <ContractDataProvider>
            <Toaster />
            <LayoutContent>
              {children}
            </LayoutContent>
          </ContractDataProvider>
        </WalletProvider>
      </body>
    </html>
  );
}

